#!/bin/bash

while [ 1 ]; do
    echo "["$(date | tr -d '\n')"] Running speed test."
    speedtest --csv >> speed.log
    sleeptime=$(($RANDOM%(7200)+1))
    echo "Waiting $sleeptime seconds."
    sleep $sleeptime
done
